### ISSUE TITLE
HTTP Error 429: Too Many Requests on the replit that you setup (https://replit.com/@Gcat101/LinkBruteforcer) 

### ISSUE THREAD

**Issue by BookmarksStack** [Gcat101/ultimate-url-bruteforcer#3]
It was definitely working, i put "y" on print failed attempts, it goes on to print the "- Failed" attempts for a while until it stops with HTTP Error 429: Too Many Requests. Do i wait it out until it could make another request or?

**Comment by Gcat101** [comment]
Which platform did you use?

**Comment by BookmarksStack** [comment]
I typed in Youtube

**Comment by Gcat101** [comment]
should work now
